name: "Bug report"
description: 发现 BUG 并反馈问题
title: ":bug: "
labels:
  - bug

body:

  - type: input
    id: os
    attributes:
      label: 操作系统
      description: |
        出现问题的操作系统及其版本
      placeholder: Windows 11 NT 10.0.26100 x86_64
    validations:
      required: true

  - type: input
    id: tex
    attributes:
      label: 环境版本
      description: |
        使用的 LaTeX 环境，如 TeXLive, MacTeX
      placeholder: TeXLive
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 问题说明及截图
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 问题复现步骤
      description: |
        请提供能复现此问题的步骤，如果包含有问题的代码请给出代码的内容或链接，这对于我们定位问题十分有帮助
    validations:
      required: true

  - type: textarea
    id: others
    attributes:
      label: 其他说明

